<?php

namespace App\Exports;

use App\Models\User;
use App\Models\Product;
use App\Models\Brand;
use App\Models\ProductCategory;
use App\Models\Coupon;
use App\Models\Offer;
use App\Models\ProductRating;
use App\Models\InventoryTransaction;
use Illuminate\Support\Facades\Auth;
use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithColumnWidths;
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;

class DashboardReportExport implements FromArray,WithStyles,WithColumnWidths,WithEvents
{
    public function array(): array
    {
        $totalCustomers = User::whereHas('role', function ($query) {
            $query->where('name', 'customer');
        })->count();

        $activeCustomers = User::whereHas('role', function ($query) {
            $query->where('name', 'customer');
        })
            ->where('status', 1)
            ->count();

        $totalProducts = Product::count();
        $activeProducts = Product::query()->where('status', 1)->count();

        $totalBrands = Brand::count();
        $activeBrands = Brand::query()->where('status', 1)->count();

        $totalCategories = ProductCategory::count();

        $totalCoupons = Coupon::count();
        $activeCoupons = Coupon::query()->where('status', 1)->count();

        $totalOffers = Offer::count();
        $activeOffers = Offer::query()->where('status', 1)->count();

        $totalStock = Product::sum('stock');

        $outOfStockProducts = Product::query()->where('stock', '<=', 0)->count();

        $lowStockProducts = Product::query()->where('stock', '>', 0)
            ->where('stock', '<=', 5)
            ->count();

        $totalRatings = ProductRating::count();
        $averageRating = ProductRating::avg('rating') ?? 0;

        $totalStockIn = InventoryTransaction::where(
            'type',
            'stock_in'
        )->sum('quantity');

        $totalStockOut = InventoryTransaction::where(
            'type',
            'stock_out'
        )->sum('quantity');

        $todayStockIn = InventoryTransaction::where(
            'type',
            'stock_in'
        )
            ->whereDate('created_at', today())
            ->sum('quantity');

        $todayStockOut = InventoryTransaction::where(
            'type',
            'stock_out'
        )
            ->whereDate('created_at', today())
            ->sum('quantity');

        $recentProducts = Product::with('category')
            ->latest()
            ->take(10)
            ->get();

        $lowStockProductList = Product::with('category')
            ->where('stock', '>', 0)
            ->where('stock', '<=', 5)
            ->orderBy('stock')
            ->take(10)
            ->get();

        $recentInventoryTransactions =
            InventoryTransaction::with([
                'product',
                'creator'
            ])
                ->latest()
                ->take(10)
                ->get();

        $rows = [];
        $rows[] = [
            'ECOMMERCE DASHBOARD REPORT'
        ];

        $rows[] = [
            'Complete Ecommerce Dashboard Summary'
        ];

        $rows[] = [
            'Generated By',
            Auth::user()->name ?? '-',
            '',
            'Generated On',
            now()->format('d M Y, h:i A')
        ];

        $rows[] = [];
        $rows[] = [
            'BUSINESS OVERVIEW'
        ];

        $rows[] = [
            'Metric',
            'Value',
            'Metric',
            'Value'
        ];

        $rows[] = [
            'Total Customers',
            $totalCustomers,
            'Active Customers',
            $activeCustomers
        ];

        $rows[] = [
            'Total Products',
            $totalProducts,
            'Active Products',
            $activeProducts
        ];

        $rows[] = [
            'Total Brands',
            $totalBrands,
            'Active Brands',
            $activeBrands
        ];

        $rows[] = [
            'Categories',
            $totalCategories,
            'Total Coupons',
            $totalCoupons
        ];

        $rows[] = [
            'Active Coupons',
            $activeCoupons,
            'Total Offers',
            $totalOffers
        ];

        $rows[] = [
            'Active Offers',
            $activeOffers,
            '',
            ''
        ];

        $rows[] = [];
        $rows[] = [
            'INVENTORY OVERVIEW'
        ];

        $rows[] = [
            'Metric',
            'Value',
            'Metric',
            'Value'
        ];

        $rows[] = [
            'Available Stock',
            $totalStock,
            'Total Stock In',
            $totalStockIn
        ];

        $rows[] = [
            'Total Stock Out',
            $totalStockOut,
            'Today Stock In',
            $todayStockIn
        ];

        $rows[] = [
            'Today Stock Out',
            $todayStockOut,
            'Low Stock Products',
            $lowStockProducts
        ];

        $rows[] = [
            'Out of Stock Products',
            $outOfStockProducts,
            'Average Rating',
            number_format($averageRating, 1) . ' / 5'
        ];

        $rows[] = [];
        $rows[] = [
            'RATING OVERVIEW'
        ];

        $rows[] = [
            'Metric',
            'Value'
        ];

        $rows[] = [
            'Average Rating',
            number_format($averageRating, 1) . ' / 5'
        ];

        $rows[] = [
            'Total Ratings',
            $totalRatings
        ];

        $rows[] = [];
        $rows[] = [
            'RECENT PRODUCTS'
        ];

        $rows[] = [
            '#',
            'Product',
            'Category',
            'Price',
            'Stock',
            'Status'
        ];

        foreach ($recentProducts as $index => $product) {

            $rows[] = [
                $index + 1,
                $product->name,
                $product->category->name ?? '-',
                $product->price ?? 0,
                $product->stock ?? 0,
                $product->status == 1
                    ? 'Active'
                    : 'Inactive'
            ];
        }

        $rows[] = [];
        $rows[] = [
            'LOW STOCK PRODUCTS'
        ];

        $rows[] = [
            '#',
            'Product',
            'Category',
            'Available Stock',
            'Status'
        ];

        foreach ($lowStockProductList as $index => $product) {

            $rows[] = [
                $index + 1,
                $product->name,
                $product->category->name ?? '-',
                $product->stock ?? 0,
                'Low Stock'
            ];
        }

        if ($lowStockProductList->isEmpty()) {

            $rows[] = [
                '',
                'No low stock products found.',
                '',
                '',
                ''
            ];
        }

        $rows[] = [];
        $rows[] = [
            'RECENT INVENTORY TRANSACTIONS'
        ];

        $rows[] = [
            '#',
            'Product',
            'Type',
            'Quantity',
            'Before',
            'After',
            'Created By',
            'Date'
        ];

        foreach ($recentInventoryTransactions as $index => $transaction) {

            $rows[] = [
                $index + 1,
                $transaction->product->name ?? 'Product Deleted',
                $transaction->type === 'stock_in'
                    ? 'Stock In'
                    : 'Stock Out',
                $transaction->quantity ?? 0,
                $transaction->stock_before ?? 0,
                $transaction->stock_after ?? 0,
                $transaction->creator->name ?? '-',
                optional($transaction->created_at)
                    ->format('d M Y, h:i A')
            ];
        }

        $rows[] = [];

        $rows[] = [
            'Dashboard Report • Generated automatically'
        ];

        return $rows;
    }

    public function columnWidths(): array
    {
        return [
            'A' => 8,
            'B' => 34,
            'C' => 24,
            'D' => 18,
            'E' => 18,
            'F' => 18,
            'G' => 24,
            'H' => 24,
        ];
    }

    public function styles(Worksheet $sheet)
    {
        return [

            1 => [
                'font' => [
                    'bold' => true,
                    'size' => 20,
                    'color' => [
                        'rgb' => 'FFFFFF'
                    ],
                ],
            ],

            2 => [
                'font' => [
                    'bold' => true,
                    'size' => 11,
                    'color' => [
                        'rgb' => 'DCEBFF'
                    ],
                ],
            ],

        ];
    }
    public function registerEvents(): array
    {
        return [

            AfterSheet::class => function (AfterSheet $event) {

                $sheet = $event->sheet->getDelegate();
                $sheet->getDefaultRowDimension()
                    ->setRowHeight(22);

                $sheet->freezePane('A6');

                $sheet->setShowGridlines(false);

                $sheet->mergeCells('A1:H1');

                $sheet->getRowDimension(1)
                    ->setRowHeight(38);

                $sheet->getStyle('A1:H1')->applyFromArray([

                    'font' => [
                        'bold' => true,
                        'size' => 20,
                        'color' => [
                            'rgb' => 'FFFFFF'
                        ],
                    ],

                    'fill' => [
                        'fillType' => Fill::FILL_SOLID,
                        'startColor' => [
                            'rgb' => '17365D'
                        ],
                    ],

                    'alignment' => [
                        'horizontal' => Alignment::HORIZONTAL_CENTER,
                        'vertical' => Alignment::VERTICAL_CENTER,
                    ],

                ]);
                $sheet->mergeCells('A2:H2');

                $sheet->getStyle('A2:H2')->applyFromArray([

                    'font' => [
                        'bold' => true,
                        'size' => 11,
                        'color' => [
                            'rgb' => '404040'
                        ],
                    ],

                    'fill' => [
                        'fillType' => Fill::FILL_SOLID,
                        'startColor' => [
                            'rgb' => 'EAF2F8'
                        ],
                    ],

                    'alignment' => [
                        'horizontal' => Alignment::HORIZONTAL_CENTER,
                    ],

                ]);
                $sheet->mergeCells('A3:H3');

                $sheet->getStyle('A3:H3')->applyFromArray([

                    'font' => [
                        'italic' => true,
                        'size' => 10,
                        'color' => [
                            'rgb' => '666666'
                        ],
                    ],

                    'alignment' => [
                        'horizontal' => Alignment::HORIZONTAL_CENTER,
                    ],

                ]);
                $sectionRows = [
                    5,
                    13,
                    20,
                    26,
                    33,
                    43,
                ];

                foreach ($sectionRows as $row) {

                    if ($sheet->getCell("A{$row}")->getValue()) {

                        $sheet->mergeCells("A{$row}:H{$row}");

                        $sheet->getStyle("A{$row}:H{$row}")
                            ->applyFromArray([

                                'font' => [
                                    'bold' => true,
                                    'size' => 13,
                                    'color' => [
                                        'rgb' => 'FFFFFF'
                                    ],
                                ],

                                'fill' => [
                                    'fillType' => Fill::FILL_SOLID,
                                    'startColor' => [
                                        'rgb' => '00ADEF'
                                    ],
                                ],

                                'alignment' => [
                                    'vertical' =>
                                        Alignment::VERTICAL_CENTER,
                                ],

                            ]);

                        $sheet->getRowDimension($row)
                            ->setRowHeight(28);
                    }
                }

                $headerRows = [
                    6,
                    27,
                    34,
                    44,
                ];

                foreach ($headerRows as $row) {

                    $sheet->getStyle("A{$row}:H{$row}")
                        ->applyFromArray([

                            'font' => [
                                'bold' => true,
                                'color' => [
                                    'rgb' => 'FFFFFF'
                                ],
                            ],

                            'fill' => [
                                'fillType' => Fill::FILL_SOLID,
                                'startColor' => [
                                    'rgb' => '2F75B5'
                                ],
                            ],

                            'alignment' => [
                                'horizontal' =>
                                    Alignment::HORIZONTAL_CENTER,
                                'vertical' =>
                                    Alignment::VERTICAL_CENTER,
                            ],

                        ]);
                }

                $lastRow = $sheet->getHighestRow();

                $sheet->getStyle(
                    "A5:H{$lastRow}"
                )->applyFromArray([

                    'borders' => [
                        'allBorders' => [
                            'borderStyle' =>
                                Border::BORDER_THIN,
                            'color' => [
                                'rgb' => 'D9E2F3'
                            ],
                        ],
                    ],

                ]);

                $sheet->getStyle('D28:D42')
                    ->getNumberFormat()
                    ->setFormatCode(
                        '₹#,##0.00'
                    );
                $sheet->getStyle(
                    "A1:H{$lastRow}"
                )->getAlignment()->setVertical(
                    Alignment::VERTICAL_CENTER
                );

                $footerRow = $lastRow;

                $sheet->mergeCells(
                    "A{$footerRow}:H{$footerRow}"
                );

                $sheet->getStyle(
                    "A{$footerRow}:H{$footerRow}"
                )->applyFromArray([

                    'font' => [
                        'italic' => true,
                        'size' => 9,
                        'color' => [
                            'rgb' => '777777'
                        ],
                    ],
                    'alignment' => [
                        'horizontal' =>
                            Alignment::HORIZONTAL_CENTER,
                    ],
                ]);
                $sheet->getPageSetup()
                    ->setOrientation(
                        \PhpOffice\PhpSpreadsheet\Worksheet\PageSetup::ORIENTATION_LANDSCAPE
                    );
                $sheet->getPageSetup()
                    ->setPaperSize(
                        \PhpOffice\PhpSpreadsheet\Worksheet\PageSetup::PAPERSIZE_A4
                    );
                $sheet->getPageSetup()
                    ->setFitToWidth(1);

                $sheet->getPageSetup()
                    ->setFitToHeight(0);

                $sheet->getPageMargins()->setTop(0.4);
                $sheet->getPageMargins()->setRight(0.3);
                $sheet->getPageMargins()->setLeft(0.3);
                $sheet->getPageMargins()->setBottom(0.4);
            },
        ];
    }
}
