<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">

    <title>Dashboard Report</title>

    <style>

        * {
            box-sizing: border-box;
        }

        body {
            font-family: DejaVu Sans, sans-serif;
            color: #333;
            font-size: 11px;
        }

        .header {
            border-bottom: 2px solid #00adef;
            padding-bottom: 15px;
            margin-bottom: 20px;
        }

        .header h1 {
            margin: 0;
            color: #222;
            font-size: 24px;
        }

        .header p {
            color: #777;
            margin: 5px 0 0;
        }

        .report-info {
            margin-bottom: 20px;
        }

        .report-info table {
            width: 100%;
        }

        .report-info td {
            padding: 4px 0;
        }

        .section-title {
            background: #f4f6f9;
            padding: 10px;
            font-size: 14px;
            font-weight: bold;
            border-left: 4px solid #00adef;
            margin-top: 20px;
            margin-bottom: 12px;
        }

        .stats-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
        }

        .stats-table td {
            width: 25%;
            padding: 12px;
            border: 1px solid #e5e5e5;
            vertical-align: top;
        }

        .stat-label {
            display: block;
            color: #777;
            font-size: 10px;
            margin-bottom: 5px;
        }

        .stat-value {
            font-size: 18px;
            font-weight: bold;
            color: #222;
        }

        .data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        .data-table th {
            background: #00adef;
            color: #fff;
            padding: 8px;
            text-align: left;
        }

        .data-table td {
            padding: 8px;
            border: 1px solid #ddd;
        }

        .text-center {
            text-align: center;
        }

        .text-right {
            text-align: right;
        }

        .footer {
            position: fixed;
            bottom: -25px;
            left: 0;
            right: 0;
            text-align: center;
            color: #777;
            font-size: 9px;
        }

    </style>
</head>

<body>

    <div class="header">
        <h1>Dashboard Report</h1>

        <p>
            Complete Ecommerce Dashboard Summary
        </p>
    </div>


    <div class="report-info">

        <table>
            <tr>
                <td>
                    <strong>Generated By:</strong>
                    {{ $user->name ?? '-' }}
                </td>

                <td class="text-right">
                    <strong>Generated On:</strong>
                    {{ now()->format('d M Y, h:i A') }}
                </td>
            </tr>
        </table>

    </div>


    <div class="section-title">
        Business Overview
    </div>

    <table class="stats-table">

        <tr>

            <td>
                <span class="stat-label">Total Customers</span>
                <span class="stat-value">
                    {{ number_format($totalCustomers) }}
                </span>
            </td>

            <td>
                <span class="stat-label">Active Customers</span>
                <span class="stat-value">
                    {{ number_format($activeCustomers) }}
                </span>
            </td>

            <td>
                <span class="stat-label">Total Products</span>
                <span class="stat-value">
                    {{ number_format($totalProducts) }}
                </span>
            </td>

            <td>
                <span class="stat-label">Active Products</span>
                <span class="stat-value">
                    {{ number_format($activeProducts) }}
                </span>
            </td>

        </tr>

        <tr>

            <td>
                <span class="stat-label">Total Brands</span>
                <span class="stat-value">
                    {{ number_format($totalBrands) }}
                </span>
            </td>

            <td>
                <span class="stat-label">Categories</span>
                <span class="stat-value">
                    {{ number_format($totalCategories) }}
                </span>
            </td>

            <td>
                <span class="stat-label">Total Coupons</span>
                <span class="stat-value">
                    {{ number_format($totalCoupons) }}
                </span>
            </td>

            <td>
                <span class="stat-label">Total Offers</span>
                <span class="stat-value">
                    {{ number_format($totalOffers) }}
                </span>
            </td>

        </tr>

    </table>


    <div class="section-title">
        Inventory Overview
    </div>

    <table class="stats-table">

        <tr>

            <td>
                <span class="stat-label">Available Stock</span>
                <span class="stat-value">
                    {{ number_format($totalStock) }}
                </span>
            </td>

            <td>
                <span class="stat-label">Total Stock In</span>
                <span class="stat-value">
                    {{ number_format($totalStockIn) }}
                </span>
            </td>

            <td>
                <span class="stat-label">Total Stock Out</span>
                <span class="stat-value">
                    {{ number_format($totalStockOut) }}
                </span>
            </td>

            <td>
                <span class="stat-label">Low Stock Products</span>
                <span class="stat-value">
                    {{ number_format($lowStockProducts) }}
                </span>
            </td>

        </tr>

        <tr>

            <td>
                <span class="stat-label">Out of Stock Products</span>
                <span class="stat-value">
                    {{ number_format($outOfStockProducts) }}
                </span>
            </td>

            <td>
                <span class="stat-label">Today Stock In</span>
                <span class="stat-value">
                    {{ number_format($todayStockIn) }}
                </span>
            </td>

            <td>
                <span class="stat-label">Today Stock Out</span>
                <span class="stat-value">
                    {{ number_format($todayStockOut) }}
                </span>
            </td>

            <td>
                <span class="stat-label">Average Rating</span>
                <span class="stat-value">
                    {{ number_format($averageRating, 1) }} / 5
                </span>
            </td>

        </tr>

    </table>


    <div class="section-title">
        Recent Products
    </div>

    <table class="data-table">

        <thead>
            <tr>
                <th>Product</th>
                <th>Category</th>
                <th>Price</th>
                <th>Stock</th>
            </tr>
        </thead>

        <tbody>

            @forelse($recentProducts as $product)

                <tr>
                    <td>{{ $product->name }}</td>
                    <td>{{ $product->category->name ?? '-' }}</td>
                    <td>₹{{ number_format($product->price ?? 0, 2) }}</td>
                    <td>{{ $product->stock ?? 0 }}</td>
                </tr>

            @empty

                <tr>
                    <td colspan="4" class="text-center">
                        No products available.
                    </td>
                </tr>

            @endforelse

        </tbody>

    </table>


    <div class="section-title">
        Low Stock Products
    </div>

    <table class="data-table">

        <thead>
            <tr>
                <th>Product</th>
                <th>Category</th>
                <th>Available Stock</th>
            </tr>
        </thead>

        <tbody>

            @forelse($lowStockProductList as $product)

                <tr>
                    <td>{{ $product->name }}</td>
                    <td>{{ $product->category->name ?? '-' }}</td>
                    <td>{{ $product->stock ?? 0 }} Units</td>
                </tr>

            @empty

                <tr>
                    <td colspan="3" class="text-center">
                        No low stock products found.
                    </td>
                </tr>

            @endforelse

        </tbody>

    </table>


    <div class="footer">
        Dashboard Report • Generated automatically
    </div>

</body>
</html>
